version: '3'

services: 
    homebridge:
        build: .
        restart: on-failure
        ports: 
            - "51826:51826"
            - "9229:9229"
        volumes: 
            - /homebridge-connexoon/node_modules
            - .:/homebridge-connexoon