version: '3'

services: 
    homebridge:
        build: .
        restart: on-failure
        ports: 
            - "51888:51888"
            - "9222:9222"
        volumes: 
            - /homebridge-connexoon/node_modules
            - .:/homebridge-connexoon